django_project/urls.py
# django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("pages.urls")),
    path('library/', include(('library_app.urls', 'library_app'), namespace='library_app')),
    path('reading-log/', include(('reading_log.urls', 'reading_log'), namespace='reading_log')),
    path('search/', include(('search.urls', 'search'))),  # Update this line
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

library_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add-book/', views.add_book, name='add_book'),
    path('book/edit/<int:book_id>/', views.edit_book, name='edit_book'),
    path('book/delete/<int:book_id>/', views.delete_book, name='delete_book'),
    path('mybooks/', views.user_books, name='user_books'),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

reading_log/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user-reading-log/', views.user_reading_log, name='user_reading_log'),
    path('add/', views.add_reading_log, name='reading_log_add'),
]

search/urls.py
from django.urls import path
from .views import search_books

app_name = 'search'

urlpatterns = [
    path('', search_books, name='search_books'),
]

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/v4-shims.min.css">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <title>{% block title %}DjangoX{% endblock title %}</title>
  <meta name="description" content="A framework for launching new Django projects quickly.">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

  {% block css %}
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% endblock %}
</head>

<body>
  <header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'home' %}" class="nav-link px-2 link-secondary">Home</a></li>
                <li><a href="{% url 'about' %}" class="nav-link px-2 link-dark">About</a></li>
                {% if user.is_authenticated %}
                <!-- Links visible only to authenticated users -->
                <li><a href="{% url 'library_app:user_books' %}" class="nav-link px-2 link-dark">My Books</a></li>
                <li><a href="{% url 'reading_log:user_reading_log' %}" class="nav-link px-2 link-dark">Reading Log</a></li>
                {% endif %}
                <li><a href="{% url 'search:search_books' %}" class="nav-link px-2 link-dark">Search</a></li>
                
            </ul>

            <div class="dropdown text-end">
                {% if user.is_authenticated %}
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ user.get_username }}
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
                </ul>
                {% else %}
                <form class="form-inline ml-auto">
                    <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
                    <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</header>


  <div class="container">
    {% block content %}
    <p>Default content...</p>
    {% endblock content %}
  </div>

  <footer class="footer bg-dark text-light mt-5">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-4">
          <h5>About Us</h5>
          <p class="text-muted">Your Personal Library and Reading Log is the ultimate destination for book lovers to keep track of their reading and discover new favorites.</p>
        </div>
        <div class="col-md-4">
          <h5>Quick Links</h5>
          <ul class="list-unstyled text-muted">
            <li><a href="{% url 'home' %}" class="text-light">Home</a></li>
            <li><a href="{% url 'about' %}" class="text-light">About</a></li>
            <li><a href="{% url 'library_app:user_books' %}" class="text-light">My Books</a></li>
            <li><a href="{% url 'reading_log:user_reading_log' %}" class="text-light">Reading Log</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h5>Contact Us</h5>
          <p class="text-muted">Email: contact@yourlibrary.com</p>
          <p class="text-muted">Phone: +123 456 7890</p>
          <div class="social-icons">
            <a href="#" class="text-light mr-2"><i class="fab fa-facebook-f"></i></a>
            <a href="#" class="text-light mr-2"><i class="fab fa-twitter"></i></a>
            <a href="#" class="text-light mr-2"><i class="fab fa-instagram"></i></a>
            <a href="#" class="text-light"><i class="fab fa-linkedin-in"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center bg-light text-dark-50 py-3">
      © 2024 Your Personal Library and Reading Log. All rights reserved.
    </div>
  </footer>
  

  {% block javascript %}
  <!-- Bootstrap JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}

</body>

</html>